### ISSUE TITLE
Vignette request

### ISSUE THREAD

**Issue by talegari** [dselivanov/mlapi#1]
Dear Dmitriy,

Thanks for you contributions to `R` ecosystem of packages, especially `text2vec`. Your work is inspiring!

I would like to adopt `mlapi` for my projects/packages. The API design used in `text2vec` seems very appropriate. Would it be a good idea top write a vignette/blog/site about `mlapi`? This will make it easier for people like me (stats background working with computers) to grasp and use it.

Regards,
Srikanth KS

**Comment by dselivanov** [comment]
Hi. This is definitely in my list. The issue is that I'm not sure it is matured enough. For example if I will find that something is really not nice with abstractions in `mlapi` and decide to break backward-compatibility  - it will hurt people already use it as template for their projects.

On other side I feel like it is more or less stable and actually think to put it to CRAN. Let me think a bit more.

**Comment by talegari** [comment]
Thanks.

It might be good idea to release a vignette version matching the mlapi version on github(not CRAN). I will use it for my internal projects keeping in mind the backward-compatibility issue.

**Comment by dselivanov** [comment]
@talegari I'm working on vignette. Hope will finish it soon.

**Comment by dselivanov** [comment]
@talegari please check initial work on vignette [here](https://github.com/dselivanov/mlapi/blob/cfcc12432510da125a1cea52ce66a350b05d5184/vignettes/developing-with-mlapi.Rmd). Could you please provide some feedback? obviously it is far from perfect - some things will need more explanation.

**Comment by talegari** [comment]
@dselivanov Thanks for the vignette draft. It looks like mlapi closely follows scikit-learn's API. The vignette explains things well and does not hand-hold too much (I like it). 

- Do you have to restrict the API to matrices alone? Excepting decomposition, the rest of the API should go well with any other datastructure too like dataframes.

- On a cursory note, A look at how `mlr` package wraps things might give some insights on deficiencies if any (Current design looks good to me right now)

- A `pipeline` API wrapping a set of transformations would be great, keeping in mind that we might want to run multiple algorithms on resamples.

**Comment by dselivanov** [comment]
Yes, I would like to limit API to matrices only - essentially most of the machine learning algorithms work with matrices, not data-frames. In my opinion data preparation step can/should be done with data frames, but all subsequent tasks should work with matrices. So at the end of data preparation user can call `model.matrix` or `sparse.model.matrix` and get matrix. This will allow to have more consistent pipeline with less data copying and greater performance. `scikit-learn` also sticks to this approach.

I didn't seriously think about pipeline API, worth to open separate issue. In the meanwhile I think I will publish mlapi 0.1 to CRAN (more or less current functionality) because I want my packages to have single denominator.

**Comment by dselivanov** [comment]
On CRAN now.
